config/routes.rb
Rails.application.routes.draw do

  root 'rooms#index'

  get 'rooms/:id' => 'rooms#show', as: :room
  get 'rooms' => 'rooms#new', as: :new_room
  post '/rooms' => 'rooms#create', as: :rooms

  get 'users/new' => 'users#new', as: :sign_up
  post '/users' => 'users#create', as: :users

  get 'log_in' => 'sessions#new', as: :log_in
  post 'log_in' => 'sessions#create'
  delete 'log_in' => 'sessions#delete', as: :log_out




  namespace :api do
    get 'rooms/:id' => 'rooms#show'
    post 'rooms/:id/messages' => 'messages#create'

  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :messages
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    @message = Message.new params.require(:message).permit(:body)

    @message.room = Room.find params[:id]

    @message.user = @current_user
    if @message.save
      render status: 201, json: @message
    else
      render status: 422, json: @message.errors
    end
  end
end

app/controllers/api/rooms_controller.rb
class Api::RoomsController < ApplicationController

  before_action :authenticate_user!

  def show
    @room = Room.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action do
    @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    if @current_user.blank?
      redirect_to log_in_path
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  def index
    @rooms = Room.all
  end

  def show
    @rooms = Room.all
    @room = Room.find params[:id]
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new params.require(:room).permit(:room_name)
    if @room.save
      # redirect_to room_path(id: @room.id)
      redirect_to root_path
    else
      render :new
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    username = params[:username]
    password = params[:password]
    password_confirm = params[:password_confirmation]

    user = User.find_by username: username
    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to root_path, notice: "You have logged in"
    else
      flash.now[:alert] = "Username and Password do not match"
      render :new
    end
  end

  def delete
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params.require(:user).permit(:username, :email, :password, :password_confirmation)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/api/messages_helper.rb
module Api::MessagesHelper
end

app/helpers/api/rooms_helper.rb
module Api::RoomsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Untaut2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/rooms/index.html.erb
<div class="row">
  <div class="list col-md-3">
    <div class="room-list">
      <%= link_to "Create Room", new_room_path %>
    </div>
    <% @rooms.each do |room| %>
      <div class="room-list">
        <%= link_to room.room_name, room_path(id: room.id) %>
      </div>
    <% end %>
  </div>
  <div class="welcome col-md-offset-3">
    <h1>Welcome to Untaut</h1>
    <p>
      Where we toe the line of blatent copyright infringement
    </p>
    <p>
      Choose an existing room from the left, or create your own
    </p>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>New Room</h1>
  <%= simple_form_for @room do |f| %>
    <%= f.input :room_name, label: "Room Name" %>
    <%= f.submit "Create Room", class: "btn btn-lg btn-success btn-block" %>


  <% end %>

</div>

app/views/rooms/show.html.erb
<div class="row">
  <div class="list col-md-3">
    <div class="room-list">
      <%= link_to "Home", root_path %>
    </div>

    <% @rooms.each do |room| %>
      <div class="room-list">
        <%= link_to room.room_name, room_path(id: room.id) %>
      </div>
    <% end %>
  </div>


  <div class="chat col-md-9">
    <h1>Welcome to <%= @room.room_name %></h1>
    <%= react_component 'Room', {room: @room} %>
  </div>
</div>

app/views/users/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Sign-Up</h1>
  <%= simple_form_for @user do |f| %>
    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation, label: "Confirm Password" %>
    <%= f.submit "Sign Up", class: "btn btn-lg btn-success btn-block" %>
  <% end %>

</div>